"""
Monday.com AI Business Intelligence Agent.

Built for LangChain 1.3.11 architecture using ChatGroq (langchain-groq).
Binds Monday BI tools, enforces zero-temperature factual responses, and handles API errors gracefully.
"""

import os
from typing import Any, Dict, List, Optional
from dotenv import load_dotenv

from langchain.agents import create_agent
from langchain_groq import ChatGroq

from tools.monday_tools import ALL_BI_TOOLS
from utils.logger import get_logger

# Initialize logger for BI Agent operations
logger = get_logger("bi_agent")

# Load environment variables from .env
load_dotenv()

# System prompt enforcing tool usage and preventing number fabrication
SYSTEM_PROMPT = """You are a senior Business Intelligence Agent for Monday.com workspaces.
Your objective is to answer executive questions about sales pipelines, work order execution status,
top customers, overdue tasks, revenue, and pending collections.

CRITICAL INSTRUCTIONS:
1. NEVER fabricate, estimate, or assume numbers, statistics, currency values, or metrics.
2. ALWAYS call the appropriate tool from your available tools to retrieve actual workspace data before answering.
3. If a question requires multiple tools (e.g. revenue and overdue items), call all required tools.
4. Present your final answer clearly with bullet points, formatted currency amounts, and concise business insights.
5. If a tool returns an error or no data is found, state that clearly to the user.
"""


class BIAgent:
    """
    Business Intelligence Agent for Monday.com, powered by Groq and compatible with LangChain 1.3.11.
    """

    def __init__(self, model_name: Optional[str] = None):
        """
        Initializes the BIAgent instance with ChatGroq and LangChain 1.3.x agent architecture.
        """
        self.api_key = os.getenv("GROQ_API_KEY")
        self.model_name = model_name or os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
        self.agent = None

        if not self.api_key or self.api_key.startswith("your_"):
            logger.error("GROQ_API_KEY is missing or unconfigured in environment variables.")
            return

        self._init_agent()

    def _init_agent(self):
        """
        Initializes Groq Chat model and builds the LangChain 1.3.x compiled state graph agent.
        """
        models_to_try = [
            self.model_name,
            "llama-3.3-70b-versatile",
            "llama3-70b-8192",
            "mixtral-8x7b-32768",
        ]
        models_to_try = list(dict.fromkeys(models_to_try))

        for m_name in models_to_try:
            try:
                logger.info(f"Initializing ChatGroq with model='{m_name}', temperature=0")
                llm = ChatGroq(
                    model=m_name,
                    temperature=0,
                    groq_api_key=self.api_key,
                )

                # Initialize LangChain 1.3.x agent via create_agent factory
                self.agent = create_agent(
                    llm,
                    ALL_BI_TOOLS,
                    system_prompt=SYSTEM_PROMPT,
                )
                logger.info(f"Successfully created LangChain 1.3.11 BI Agent using Groq model '{m_name}'.")
                return
            except Exception as e:
                logger.warning(f"Failed to initialize model '{m_name}': {str(e)}")

        logger.error("Failed to initialize BIAgent across candidate Groq models.")

    def ask(self, question: str) -> str:
        """
        Accepts a natural language business question, routes it through the AI Agent,
        allowing the agent to choose the correct tool, and returns the answer as plain text.

        Args:
            question (str): Natural language business question.

        Returns:
            str: Plain text answer generated by the agent based on tool results.
        """
        logger.info(f"BIAgent receiving question: '{question}'")

        if not self.agent:
            logger.error("BIAgent not initialized. Cannot answer question.")
            return (
                "Error: Unable to initialize AI Agent. Please ensure GROQ_API_KEY "
                "is configured correctly in your .env file."
            )

        try:
            # LangChain 1.3.x state graph invocation format
            response = self.agent.invoke({
                "messages": [{"role": "user", "content": question}]
            })

            messages = response.get("messages", [])
            if messages:
                last_message = messages[-1]
                content = getattr(last_message, "content", str(last_message))

                if isinstance(content, list):
                    text_parts = [
                        p.get("text", "") for p in content if isinstance(p, dict) and "text" in p
                    ]
                    return "\n".join(text_parts) if text_parts else str(content)

                return str(content)

            return "No response generated by the agent."

        except Exception as e:
            error_msg = str(e)
            logger.error(f"Error occurred during BIAgent question execution: {error_msg}")
            return f"An error occurred while processing your query: {error_msg}"


# Default singleton instance for module-level ask function
_default_bi_agent = BIAgent()


def ask(question: str) -> str:
    """
    Module-level function accepting a natural language business question,
    routing it through the BIAgent, and returning the answer as plain text.

    Args:
        question (str): Natural language query.

    Returns:
        str: Plain text response from the AI agent.
    """
    return _default_bi_agent.ask(question)
